config/routes.rb
Shopeng::Engine.routes.draw do
  
  get 'show/index', :to => 'public#index'
  get 'show/:id', :to => 'public#show'

  resources :items

  resources :categories do
  	resources :items
  end

end

app/models/shopeng/category.rb
module Shopeng
  class Category < ActiveRecord::Base
  	has_many :items
  end
end

app/models/shopeng/item.rb
module Shopeng
  class Item < ActiveRecord::Base
  	mount_uploader :image, ItemImageUploader
  	belongs_to :category
  end
end

app/models/shopeng/public.rb
module Shopeng
  class Public < ActiveRecord::Base
    def next
		if Item.order("id ASC").where("id > ?", id).first
	
	end

	def previous
		Item.order("id DESC").where("id < ?", id).last
	end

  end
end

app/controllers/shopeng/application_controller.rb
class Shopeng::ApplicationController < ApplicationController
end

app/controllers/shopeng/categories_controller.rb
require_dependency "shopeng/application_controller"

module Shopeng
  class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update, :destroy]

    # GET /categories
    def index
      @categories = Category.all
    end

    # GET /categories/1
    def show
    end

    # GET /categories/new
    def new
      @category = Category.new
    end

    # GET /categories/1/edit
    def edit
    end

    # POST /categories
    def create
      @category = Category.new(category_params)

      if @category.save
        redirect_to @category, notice: 'Category was successfully created.'
      else
        render action: 'new'
      end
    end

    # PATCH/PUT /categories/1
    def update
      if @category.update(category_params)
        redirect_to @category, notice: 'Category was successfully updated.'
      else
        render action: 'edit'
      end
    end

    # DELETE /categories/1
    def destroy
      @category.destroy
      redirect_to categories_url, notice: 'Category was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_category
        @category = Category.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def category_params
        params.require(:category).permit(:title)
      end
  end
end

app/controllers/shopeng/items_controller.rb
require_dependency "shopeng/application_controller"

module Shopeng
  class ItemsController < ApplicationController
    before_action :set_item, only: [:show, :edit, :update, :destroy]

    # GET /items
    def index
      @items = Item.all
    end

    # GET /items/1
    def show
    end

    # GET /items/new
    def new
      @item = Item.new
      @item.category_id = params[:category_id]
    end

    # GET /items/1/edit
    def edit
    end

    # POST /items
    def create
      @item = Item.new(item_params)

      if @item.save
        redirect_to @item, notice: 'Item was successfully created.'
      else
        render action: 'new'
      end
    end

    # PATCH/PUT /items/1
    def update
      if @item.update(item_params)
        redirect_to @item, notice: 'Item was successfully updated.'
      else
        render action: 'edit'
      end
    end

    # DELETE /items/1
    def delete
      @item = Item.find(params[:id])
    end

    def destroy
      @item.destroy
      redirect_to items_path, notice: 'Item was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_item
        @item = Item.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def item_params
        params.require(:item).permit(:title, :text, :price, :category_id, :image)
      end
  end
end

app/controllers/shopeng/public_controller.rb
require_dependency "shopeng/application_controller"

module Shopeng
  class PublicController < ApplicationController
    
  	before_action :setup_navigation

    def index
      @items = Item.all
      @item = Item.all
    end

    def show
      @items = Item.all
      @item = Item.where(:id => params[:id]).first
        if @item.nil?
          redirect_to(:action => 'index')
        else
        end
    end

    private 

    def setup_navigation
    	@categories
    end
  end
end

app/helpers/shopeng/application_helper.rb
module Shopeng
  module ApplicationHelper
  end
end

app/helpers/shopeng/categories_helper.rb
module Shopeng
  module CategoriesHelper
  end
end

app/helpers/shopeng/items_helper.rb
module Shopeng
  module ItemsHelper
  end
end

app/helpers/shopeng/public_helper.rb
module Shopeng
  module PublicHelper
  end
end

app/views/layouts/shopeng/__navigation.html.erb
<div class="container">
	<h1><%= notice %></h1>

	<div class="row">
		<strong>Title:</strong>
	
	</div>

	<% @items.each do |item| %>
	  <div>
		<div class="col-md-3">	
			<div class="well">
				<%= image_tag item.image_url(:thumb).to_s %>
				<h3><%= item.title %></h3>

				<p>
					<%= truncate(item.text, length: 80, omission: "...") %>
				</p>
				<p>
					<%= link_to "View details", '1', :class => 'btn btn-default' %>
				</p>
			</div>
		</div>
	  </div>
	
	<% end %>

<ul>

app/views/layouts/shopeng/_navigation.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>

  <div class="row">
	<div class="col-md-4">
		<div class="well">

			<p>
			  <strong>Title:</strong>
			  <%= @item.title %>
			</p>

			<p>
			  <strong>Text:</strong>
			  <%= @item.text %>
			</p>

			<p>
			  <strong>Price:</strong>
			  <%= @item.price %>
			</p>
		
			<p>
			  <strong>Thumb:</strong><br />
			  <%= image_tag @item.image_url(:thumb).to_s %>
			</p>
		
		 
			<%= link_to 'Back', items_path, :class => 'btn btn-primary' %>
		</div>
	</div>
  </div>
</div>

app/views/layouts/shopeng/publict.html.erb
<!DOCTYPE html>
<html>
	<div class="navigation">
		<%= render(:partial => 'layouts/shopeng/navigation', :locals => {:items => @items }) %>
	</div>
</html>

app/views/shopeng/categories/_form.html.erb
<div class="container">
  <%= form_for(@category) do |f| %>
    <% if @category.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

        <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <br />
    
      <%= f.submit "Submit", class: 'btn btn-large btn-default' %>
    
    <hr>
  <% end %>
</div>

app/views/shopeng/categories/edit.html.erb
<div class="container">
	<h1>Editing category</h1>

	<%= render 'form' %>

	<hr>

	<%= link_to 'Show', @category, :class => "btn btn-primary" %> 
	<%= link_to 'Back', categories_path, :class => "btn btn-default" %>
</div>

app/views/shopeng/categories/index.html.erb
<div class="container">
  <h1>Listing categories</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
  

    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.title %></td>
            <td class=""col-md-4>
              <%= link_to 'Show', category, :class => 'btn btn-primary' %>
              <%= link_to 'Edit', edit_category_path(category), :class => 'btn btn-default' %>
              <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
            </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Category', new_category_path, :class => 'btn btn-primary' %>



</div>

app/views/shopeng/categories/new.html.erb
<div class="container">
	<h1>New category</h1>

	<%= render 'form' %>

	<%= link_to 'Back', categories_path, :class => 'btn btn-primary' %>
</div>

app/views/shopeng/categories/show.html.erb
<div class="container">
	<h1><%= notice %></h1>

	<div class="row">
		<strong>Title:</strong>
		<%= @category.title %>
	

		<% @category.items.each do |item| %>
		  <div>
			<div class="col-md-3">	
				<div class="well">
					<%= image_tag item.image_url(:thumb).to_s %>
					<h3><%= item.title %></h3>

					<p>
						<%= truncate(item.text, length: 80, omission: "...") %>
					</p>
					<p>
						<%= link_to "View details", item_path(item), :class => 'btn btn-default' %>
					</p>
				</div>
			</div>
		  </div>
		<% end %>
	</div>

	<div class="btn">
		<%= link_to 'Edit', edit_category_path(@category), :class => 'btn btn-primary ' %> 
		<%= link_to 'Back', categories_path, :class => 'btn btn-default' %>
		<%= link_to 'New item', new_category_item_path(@category), :class => 'btn btn-info' %>
	</div>
	<hr>
	<%= link_to("Back to Menu", main_app.admin_url, :class => 'btn btn-primary btn-lg') %>
</div>

app/views/shopeng/items/_form.html.erb
  <%= form_for(@item, :multipart => true) do |f| %>
    <% if @item.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:
        </h2>

        <ul>
          <% @item.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :text %><br />
      <%= f.text_area :text %>
    </div>
    <div class="field">
      <%= f.label :price %><br />
      <%= f.text_field :price %>
    </div>
    <div class="field">
      <%= f.label :image %><br />
      <%= f.file_field :image %>
    </div>
    <div class="field">
      <%= f.hidden_field :category_id %><br />
    </div>
    <div class="actions">
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </div>
    <br /><br />
  <% end %>

app/views/shopeng/items/delete.html.erb
<%= link_to("<< Back to list", {:action => 'index'}, :class => 'back-link') %>

<div class="items delete">
	<h2>Delete Item</h2>

	<%= form_tag({:action => 'destroy', :id => @item.id}) do %>

		<p>Are you sure you want to permanently delete this item?</p>

		<p class="reference-name"><%= @item.image_url %></p>

		<div class="form-buttons">
			<%= submit_tag("Delete item") %>
		</div>
	<% end %>
</div>

app/views/shopeng/items/edit.html.erb
<div class="container">
	<div class="row">
		<h1>Editing item</h1>
			<%= render 'form' %>

	

		<%= link_to 'Show', @item, :class => 'btn btn-default' %> 
		<%= link_to 'Back', items_path, :class => 'btn btn-primary' %>
	</div>
</div>

app/views/shopeng/items/index.html.erb
<div class="container">
  <h1>Listing items</h1>

      <table class="table table-striped">
          <thead>
                <tr>
                  <th class="col-md-5">Title</th>
                  <th class="col-md-5">Text</th> 
                  
                </tr>
          </thead>
     
          <tbody>
              <% @items.each do |item| %>
                    <tr>
                      <td><%= item.title %></td>
                      <td><%= item.text %></td>
                      
                    
                     <td><%= link_to 'Show', item, :class => 'btn btn-default' %></td>  
                      <td><%= link_to 'Edit', edit_item_path(item.id), :class => 'btn btn-primary' %></td>
                      <td><%= link_to 'Remove', item, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-danger' %></td>
                    </tr>
              <% end %>
          </tbody>
      </table>

      <br>

        <%= link_to 'New Item', new_item_path, :class => 'btn btn-info' %><hr>
        <%= link_to("Back to Menu", main_app.admin_url, :class => 'btn btn-primary btn-lg') %>
</div>

app/views/shopeng/items/new.html.erb
<div class="container">
	<h1>New item</h1>

	<%= render 'form' %>

	<%= link_to 'Back', items_path, :class => 'btn btn-primary' %>
</div>

app/views/shopeng/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @item.text %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category_id %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>